users = [
    {"id": 1, "name": "Arjun", "email": "arjun1@example.com", "age": 28, "country": "India", "is_married": False},
    {"id": 2, "name": "Meera", "email": "meera2@example.com", "age": 34, "country": "India", "is_married": True},
    {"id": 3, "name": "Rahul", "email": "rahul3@example.com", "age": 26, "country": "India", "is_married": False},
    {"id": 4, "name": "Ananya", "email": "ananya4@example.com", "age": 31, "country": "USA", "is_married": True},
    {"id": 5, "name": "Vikram", "email": "vikram5@example.com", "age": 38, "country": "Canada", "is_married": True},
    {"id": 6, "name": "Pooja", "email": "pooja6@example.com", "age": 25, "country": "India", "is_married": False},
    {"id": 7, "name": "Karthik", "email": "karthik7@example.com", "age": 33, "country": "India", "is_married": True},
    {"id": 8, "name": "Sneha", "email": "sneha8@example.com", "age": 27, "country": "India", "is_married": False},
    {"id": 9, "name": "Amit", "email": "amit9@example.com", "age": 41, "country": "USA", "is_married": True},
    {"id": 10, "name": "Neha", "email": "neha10@example.com", "age": 29, "country": "India", "is_married": False},

    {"id": 11, "name": "Rohit", "email": "rohit11@example.com", "age": 35, "country": "India", "is_married": True},
    {"id": 12, "name": "Kavya", "email": "kavya12@example.com", "age": 24, "country": "UK", "is_married": False},
    {"id": 13, "name": "Suresh", "email": "suresh13@example.com", "age": 46, "country": "India", "is_married": True},
    {"id": 14, "name": "Divya", "email": "divya14@example.com", "age": 32, "country": "Australia", "is_married": True},
    {"id": 15, "name": "Manoj", "email": "manoj15@example.com", "age": 39, "country": "India", "is_married": True},
    {"id": 16, "name": "Aishwarya", "email": "aishwarya16@example.com", "age": 26, "country": "India", "is_married": False},
    {"id": 17, "name": "Pranav", "email": "pranav17@example.com", "age": 34, "country": "Germany", "is_married": True},
    {"id": 18, "name": "Ritu", "email": "ritu18@example.com", "age": 28, "country": "India", "is_married": False},
    {"id": 19, "name": "Nikhil", "email": "nikhil19@example.com", "age": 30, "country": "India", "is_married": False},
    {"id": 20, "name": "Isha", "email": "isha20@example.com", "age": 37, "country": "USA", "is_married": True},

    {"id": 21, "name": "Deepak", "email": "deepak21@example.com", "age": 44, "country": "India", "is_married": True},
    {"id": 22, "name": "Shreya", "email": "shreya22@example.com", "age": 23, "country": "India", "is_married": False},
    {"id": 23, "name": "Harsha", "email": "harsha23@example.com", "age": 36, "country": "India", "is_married": True},
    {"id": 24, "name": "Pallavi", "email": "pallavi24@example.com", "age": 29, "country": "UK", "is_married": False},
    {"id": 25, "name": "Ravi", "email": "ravi25@example.com", "age": 42, "country": "India", "is_married": True},
    {"id": 26, "name": "Nandini", "email": "nandini26@example.com", "age": 27, "country": "India", "is_married": False},
    {"id": 27, "name": "Kunal", "email": "kunal27@example.com", "age": 35, "country": "Canada", "is_married": True},
    {"id": 28, "name": "Bhavya", "email": "bhavya28@example.com", "age": 31, "country": "India", "is_married": False},
    {"id": 29, "name": "Sanjay", "email": "sanjay29@example.com", "age": 48, "country": "India", "is_married": True},
    {"id": 30, "name": "Tanvi", "email": "tanvi30@example.com", "age": 26, "country": "Australia", "is_married": False},

    {"id": 31, "name": "Akash", "email": "akash31@example.com", "age": 34, "country": "India", "is_married": True},
    {"id": 32, "name": "Rashmi", "email": "rashmi32@example.com", "age": 28, "country": "India", "is_married": False},
    {"id": 33, "name": "Varun", "email": "varun33@example.com", "age": 37, "country": "USA", "is_married": True},
    {"id": 34, "name": "Swati", "email": "swati34@example.com", "age": 25, "country": "India", "is_married": False},
    {"id": 35, "name": "Yash", "email": "yash35@example.com", "age": 29, "country": "India", "is_married": False},
    {"id": 36, "name": "Komal", "email": "komal36@example.com", "age": 33, "country": "UK", "is_married": True},
    {"id": 37, "name": "Abhishek", "email": "abhishek37@example.com", "age": 41, "country": "India", "is_married": True},
    {"id": 38, "name": "Riya", "email": "riya38@example.com", "age": 24, "country": "India", "is_married": False},
    {"id": 39, "name": "Siddharth", "email": "siddharth39@example.com", "age": 35, "country": "Germany", "is_married": True},
    {"id": 40, "name": "Priya", "email": "priya40@example.com", "age": 30, "country": "India", "is_married": False},

    {"id": 41, "name": "Gaurav", "email": "gaurav41@example.com", "age": 43, "country": "India", "is_married": True},
    {"id": 42, "name": "Anjali", "email": "anjali42@example.com", "age": 27, "country": "India", "is_married": False},
    {"id": 43, "name": "Mayank", "email": "mayank43@example.com", "age": 38, "country": "USA", "is_married": True},
    {"id": 44, "name": "Sakshi", "email": "sakshi44@example.com", "age": 26, "country": "India", "is_married": False},
    {"id": 45, "name": "Vivek", "email": "vivek45@example.com", "age": 40, "country": "India", "is_married": True},
    {"id": 46, "name": "Priti", "email": "priti46@example.com", "age": 31, "country": "UK", "is_married": True},
    {"id": 47, "name": "Ashwin", "email": "ashwin47@example.com", "age": 28, "country": "India", "is_married": False},
    {"id": 48, "name": "Namrata", "email": "namrata48@example.com", "age": 34, "country": "India", "is_married": True},
    {"id": 49, "name": "Rakesh", "email": "rakesh49@example.com", "age": 46, "country": "India", "is_married": True},
    {"id": 50, "name": "Mitali", "email": "mitali50@example.com", "age": 29, "country": "Canada", "is_married": False},

    {"id": 51, "name": "Sameer", "email": "sameer51@example.com", "age": 36, "country": "India", "is_married": True},
    {"id": 52, "name": "Payal", "email": "payal52@example.com", "age": 25, "country": "India", "is_married": False},
    {"id": 53, "name": "Uday", "email": "uday53@example.com", "age": 42, "country": "Australia", "is_married": True},
    {"id": 54, "name": "Sonal", "email": "sonal54@example.com", "age": 28, "country": "India", "is_married": False},
    {"id": 55, "name": "Naveen", "email": "naveen55@example.com", "age": 39, "country": "India", "is_married": True},
    {"id": 56, "name": "Aditi", "email": "aditi56@example.com", "age": 24, "country": "India", "is_married": False},
    {"id": 57, "name": "Ramesh", "email": "ramesh57@example.com", "age": 50, "country": "India", "is_married": True},
    {"id": 58, "name": "Kiran", "email": "kiran58@example.com", "age": 33, "country": "UK", "is_married": True},
    {"id": 59, "name": "Mohit", "email": "mohit59@example.com", "age": 27, "country": "India", "is_married": False},
    {"id": 60, "name": "Simran", "email": "simran60@example.com", "age": 31, "country": "Canada", "is_married": True},

    {"id": 61, "name": "Jay", "email": "jay61@example.com", "age": 29, "country": "India", "is_married": False},
    {"id": 62, "name": "Pankhuri", "email": "pankhuri62@example.com", "age": 35, "country": "USA", "is_married": True},
    {"id": 63, "name": "Arvind", "email": "arvind63@example.com", "age": 44, "country": "India", "is_married": True},
    {"id": 64, "name": "Chitra", "email": "chitra64@example.com", "age": 28, "country": "India", "is_married": False},
    {"id": 65, "name": "Sunil", "email": "sunil65@example.com", "age": 47, "country": "India", "is_married": True},
    {"id": 66, "name": "Lavanya", "email": "lavanya66@example.com", "age": 26, "country": "India", "is_married": False},
    {"id": 67, "name": "Dev", "email": "dev67@example.com", "age": 34, "country": "Germany", "is_married": True},
    {"id": 68, "name": "Nisha", "email": "nisha68@example.com", "age": 32, "country": "India", "is_married": True},
    {"id": 69, "name": "Prakash", "email": "prakash69@example.com", "age": 41, "country": "India", "is_married": True},
    {"id": 70, "name": "Kritika", "email": "kritika70@example.com", "age": 25, "country": "India", "is_married": False},

    {"id": 71, "name": "Ajay", "email": "ajay71@example.com", "age": 38, "country": "India", "is_married": True},
    {"id": 72, "name": "Monika", "email": "monika72@example.com", "age": 29, "country": "UK", "is_married": False},
    {"id": 73, "name": "Raj", "email": "raj73@example.com", "age": 45, "country": "India", "is_married": True},
    {"id": 74, "name": "Tanya", "email": "tanya74@example.com", "age": 27, "country": "Canada", "is_married": False},
    {"id": 75, "name": "Shivam", "email": "shivam75@example.com", "age": 31, "country": "India", "is_married": True},
    {"id": 76, "name": "Rupal", "email": "rupal76@example.com", "age": 34, "country": "India", "is_married": True},
    {"id": 77, "name": "Vishal", "email": "vishal77@example.com", "age": 36, "country": "USA", "is_married": True},
    {"id": 78, "name": "Kajal", "email": "kajal78@example.com", "age": 24, "country": "India", "is_married": False},
    {"id": 79, "name": "Ankit", "email": "ankit79@example.com", "age": 28, "country": "India", "is_married": False},
    {"id": 80, "name": "Juhi", "email": "juhi80@example.com", "age": 33, "country": "UK", "is_married": True},

    {"id": 81, "name": "Hemant", "email": "hemant81@example.com", "age": 42, "country": "India", "is_married": True},
    {"id": 82, "name": "Rachna", "email": "rachna82@example.com", "age": 30, "country": "India", "is_married": False},
    {"id": 83, "name": "Saurabh", "email": "saurabh83@example.com", "age": 37, "country": "India", "is_married": True},
    {"id": 84, "name": "Ishita", "email": "ishita84@example.com", "age": 26, "country": "India", "is_married": False},
    {"id": 85, "name": "Alok", "email": "alok85@example.com", "age": 48, "country": "India", "is_married": True},
    {"id": 86, "name": "Preeti", "email": "preeti86@example.com", "age": 35, "country": "Canada", "is_married": True},
    {"id": 87, "name": "Nitin", "email": "nitin87@example.com", "age": 39, "country": "India", "is_married": True},
    {"id": 88, "name": "Sheetal", "email": "sheetal88@example.com", "age": 29, "country": "India", "is_married": False},
    {"id": 89, "name": "Rohil", "email": "rohil89@example.com", "age": 34, "country": "UK", "is_married": True},
    {"id": 90, "name": "Ankita", "email": "ankita90@example.com", "age": 27, "country": "India", "is_married": False},

    {"id": 91, "name": "Keshav", "email": "keshav91@example.com", "age": 41, "country": "India", "is_married": True},
    {"id": 92, "name": "Suman", "email": "suman92@example.com", "age": 36, "country": "India", "is_married": True},
    {"id": 93, "name": "Tarun", "email": "tarun93@example.com", "age": 32, "country": "USA", "is_married": True},
    {"id": 94, "name": "Pooja", "email": "pooja94@example.com", "age": 28, "country": "India", "is_married": False},
    {"id": 95, "name": "Lokesh", "email": "lokesh95@example.com", "age": 44, "country": "India", "is_married": True},
    {"id": 96, "name": "Bharti", "email": "bharti96@example.com", "age": 31, "country": "India", "is_married": True},
    {"id": 97, "name": "Arnav", "email": "arnav97@example.com", "age": 25, "country": "India", "is_married": False},
    {"id": 98, "name": "Ruchi", "email": "ruchi98@example.com", "age": 34, "country": "Canada", "is_married": True},
    {"id": 99, "name": "Sandeep", "email": "sandeep99@example.com", "age": 46, "country": "India", "is_married": True},
    {"id": 100, "name": "Piyush", "email": "piyush100@example.com", "age": 29, "country": "India", "is_married": False},
]
